DATA = { "ABACUS" : "An early counting tool used for basic arithmetic",
"AREA" : "The extent of a surface measured in m²", 
"BUG" : "Refers to a broken code with a fault or flaw",
"CAD(Computer-Aided Design)" : "A software system used by engineers to create 3D models",
"CALCULUS" : "The branch of mathematics involving derivatives and integrals",
"CAPACITY" : "The volume of substance that a container will hold",
"CLOUD" : "A remote internet storage solution",
"CODING" : "How people create instructions for computers to follow",
"COMPUTER PROGRAM" : "A collection of codes that tell a computer what to do",
"CONCAVITY" : "The upward or downward curve of the graph of a function",
"CONSTANT" : "A value that does not change",
"DEPENDENT VARIABLE" : "The output variable for a function",
"DENSITY" : "Mass per unit volume",
"DOMAIN" : "The set of inputs for a function",
"FORCE" : "A mysterious interaction between objects",
"GRAVITY" : "One of the four fundamental forces of nature",
"INPUT" : "Any interaction from the user to the program",
"JAVA" : "A powerful multi-platform programming language",
"LENGTH" : "The distance between two points",
"MASS" : "A measure of the quantity of matter, independent of its volume",
"MATTER" : "Stuff that the world is made of",
"MOMENTUM" : "The product of speed and velocity - a vector quantity",
"POWER" : "The rate of doing work",
"PYTHON" : "A programming language that is currently becoming more and more powerful",
"RANGE" : "The set of outputs for a function",
"SLOPE" : "The change in y for each unit change in x",
"STRING" : "Variables can hold data besides numbers, including words",
"SURFACE AREA" : "A total area of the outer layer of the object",
"TABLE OF VALUES" : "A table containing a list of inputs and their corresponding outputs",
"THERMAL CONDUCTIVITY" : "The ability of a material to conduct heat" }

a = input("Say 'ABACUS,' 'AREA', 'BUG', 'CAD(Computer-Aided Design)', 'CALCULUS', 'CAPACITY', 'CLOUD,' 'CODING', 'COMPUTER PROGRAM', 'CONCAVITY', 'CONSTANT', 'DEPENDENT VARIABLE', 'DENSITY', 'DOMAIN', 'FORCE', 'GRAVITY', 'INPUT', 'JAVA', 'LENGTH', 'MASS', 'MATTER', 'MOMENTUM', 'POWER', 'PYTHON', 'RANGE', 'SLOPE', 'STRING', 'SURFACE AREA', 'TABLE OF VALUES', 'THERMAL CONDUCTIVITY' ")
print (DATA[a])